[package]
name = "supercov-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
base64.workspace = true
flate2.workspace = true
libc.workspace = true
memmap2.workspace = true
reflink-copy.workspace = true
oxc_allocator.workspace = true
oxc_ast.workspace = true
oxc_ast_visit.workspace = true
oxc_codegen.workspace = true
oxc_parser.workspace = true
oxc_semantic.workspace = true
oxc_sourcemap.workspace = true
oxc_span.workspace = true
oxc_syntax.workspace = true
oxc_traverse.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
supercov-contracts.workspace = true
sysinfo.workspace = true

[build-dependencies]
sha2.workspace = true
