#!/usr/bin/env node
// Generate the Homebrew formula for a release, with the real checksums.
//
// The tap is how someone installs Supercov without first installing Node,
// Python, Ruby or Rust -- which, before this, was the only way in for a Go or
// JVM project. The formula points at the same archives every other channel
// publishes, so there is nothing extra to build or upload.
//
// A formula has to carry a sha256 per platform, and those change every
// release, so this is generated rather than edited. Run it after the release
// is published and commit the result to the tap:
//
//   node scripts/brew-formula.mjs 0.0.49 > Formula/supercov.rb
//
// Usage: node scripts/brew-formula.mjs [version]  (defaults to package.json)
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const repository = resolve(import.meta.dirname, "..");
const version =
  process.argv[2] ??
  JSON.parse(readFileSync(resolve(repository, "package.json"), "utf8")).version;
const base = `https://github.com/supercorp-ai/supercov/releases/download/v${version}`;

// Homebrew supports macOS and Linux. The musl builds are for systems Homebrew
// does not target, and the Windows ones have no formula at all.
const platforms = [
  { block: "on_macos", cpu: "on_arm", asset: `supercov-cli-darwin-arm64-${version}.tgz` },
  { block: "on_macos", cpu: "on_intel", asset: `supercov-cli-darwin-x64-${version}.tgz` },
  { block: "on_linux", cpu: "on_arm", asset: `supercov-cli-linux-arm64-gnu-${version}.tgz` },
  { block: "on_linux", cpu: "on_intel", asset: `supercov-cli-linux-x64-gnu-${version}.tgz` },
];

async function checksum(asset) {
  const response = await fetch(`${base}/${asset}`, { redirect: "follow" });
  if (!response.ok) {
    throw new Error(`${asset}: ${response.status} ${response.statusText}`);
  }
  return createHash("sha256")
    .update(Buffer.from(await response.arrayBuffer()))
    .digest("hex");
}

for (const platform of platforms) {
  platform.sha256 = await checksum(platform.asset);
}

const section = (block) => {
  const inner = platforms
    .filter((platform) => platform.block === block)
    .map(
      (platform) =>
        `    ${platform.cpu} do\n` +
        `      url "${base}/${platform.asset}"\n` +
        `      sha256 "${platform.sha256}"\n` +
        `    end`,
    )
    .join("\n\n");
  return `  ${block} do\n${inner}\n  end`;
};

process.stdout.write(`# Generated by scripts/brew-formula.mjs. Do not edit by hand.
class Supercov < Formula
  desc "Coverage for coding agents and software factories"
  homepage "https://supercov.com"
  version "${version}"
  license "MIT"

${section("on_macos")}

${section("on_linux")}

  def install
    # Every channel ships the same npm package, with the binary at package/bin.
    bin.install "package/bin/supercov"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/supercov --version")
  end
end
`);
