import nativeAssert from "node:assert";
import { createNodeAssertAdapter, setStrictAssertAdapter } from "./nodeAssertAdapter.ts";

const adapter = createNodeAssertAdapter(nativeAssert, "node:assert");
const strictAdapter = createNodeAssertAdapter(nativeAssert.strict, "node:assert/strict");
setStrictAssertAdapter(adapter, strictAdapter);
setStrictAssertAdapter(strictAdapter, strictAdapter);

export default adapter;
export const Assert = adapter.Assert;
export const AssertionError = adapter.AssertionError;
export const CallTracker = adapter.CallTracker;
export const deepEqual = adapter.deepEqual;
export const deepStrictEqual = adapter.deepStrictEqual;
export const doesNotMatch = adapter.doesNotMatch;
export const doesNotReject = adapter.doesNotReject;
export const doesNotThrow = adapter.doesNotThrow;
export const equal = adapter.equal;
export const fail = adapter.fail;
export const ifError = adapter.ifError;
export const match = adapter.match;
export const notDeepEqual = adapter.notDeepEqual;
export const notDeepStrictEqual = adapter.notDeepStrictEqual;
export const notEqual = adapter.notEqual;
export const notStrictEqual = adapter.notStrictEqual;
export const ok = adapter.ok;
export const partialDeepStrictEqual = adapter.partialDeepStrictEqual;
export const rejects = adapter.rejects;
export const strict = strictAdapter;
export const strictEqual = adapter.strictEqual;
export const throws = adapter.throws;
