[package]
name = "supercov-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "supercov"
path = "src/main.rs"

[dependencies]
supercov-contracts.workspace = true
supercov-engine.workspace = true
